name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 5m
          script: |
            cd ~/source/BlackTeaWeb
            git pull origin master
            sudo systemctl stop blacktea-web
            dotnet publish BlackTeaWeb/BlackTeaWeb.csproj -o ~/blackTeaWeb 
            sudo systemctl start blacktea-web
            
