name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 5m
          script: |
            cd ~/source/blackTeaWeb
            git pull origin master
            service blackTeaWeb stop
            dotnet publish -o ~/blackTeaWeb
            service blackTeaWeb start
            
